Traceback (most recent call last):
  File "/__w/notes/notes/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/notes/notes/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/__w/notes/notes/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/__w/notes/notes/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/__w/notes/notes/.venv/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/__w/notes/notes/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/__w/notes/notes/.venv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# ãƒ‘ã‚¹å›³
semopy.semplot(model, filename="/tmp/path_diagram.png")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m/__w/notes/notes/.venv/lib/python3.10/site-packages/graphviz/backend/execute.py:78[0m, in [0;36mrun_check[0;34m(cmd, input_lines, encoding, quiet, **kwargs)[0m
[1;32m     77[0m     [38;5;28;01melse[39;00m:
[0;32m---> 78[0m         proc [38;5;241m=[39m [43msubprocess[49m[38;5;241;43m.[39;49m[43mrun[49m[43m([49m[43mcmd[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m     79[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m e:

File [0;32m/usr/local/lib/python3.10/subprocess.py:503[0m, in [0;36mrun[0;34m(input, capture_output, timeout, check, *popenargs, **kwargs)[0m
[1;32m    501[0m     kwargs[[38;5;124m'[39m[38;5;124mstderr[39m[38;5;124m'[39m] [38;5;241m=[39m PIPE
[0;32m--> 503[0m [38;5;28;01mwith[39;00m [43mPopen[49m[43m([49m[38;5;241;43m*[39;49m[43mpopenargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m [38;5;28;01mas[39;00m process:
[1;32m    504[0m     [38;5;28;01mtry[39;00m:

File [0;32m/usr/local/lib/python3.10/subprocess.py:971[0m, in [0;36mPopen.__init__[0;34m(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize)[0m
[1;32m    968[0m             [38;5;28mself[39m[38;5;241m.[39mstderr [38;5;241m=[39m io[38;5;241m.[39mTextIOWrapper([38;5;28mself[39m[38;5;241m.[39mstderr,
[1;32m    969[0m                     encoding[38;5;241m=[39mencoding, errors[38;5;241m=[39merrors)
[0;32m--> 971[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_execute_child[49m[43m([49m[43margs[49m[43m,[49m[43m [49m[43mexecutable[49m[43m,[49m[43m [49m[43mpreexec_fn[49m[43m,[49m[43m [49m[43mclose_fds[49m[43m,[49m
[1;32m    972[0m [43m                        [49m[43mpass_fds[49m[43m,[49m[43m [49m[43mcwd[49m[43m,[49m[43m [49m[43menv[49m[43m,[49m
[1;32m    973[0m [43m                        [49m[43mstartupinfo[49m[43m,[49m[43m [49m[43mcreationflags[49m[43m,[49m[43m [49m[43mshell[49m[43m,[49m
[1;32m    974[0m [43m                        [49m[43mp2cread[49m[43m,[49m[43m [49m[43mp2cwrite[49m[43m,[49m
[1;32m    975[0m [43m                        [49m[43mc2pread[49m[43m,[49m[43m [49m[43mc2pwrite[49m[43m,[49m
[1;32m    976[0m [43m                        [49m[43merrread[49m[43m,[49m[43m [49m[43merrwrite[49m[43m,[49m
[1;32m    977[0m [43m                        [49m[43mrestore_signals[49m[43m,[49m
[1;32m    978[0m [43m                        [49m[43mgid[49m[43m,[49m[43m [49m[43mgids[49m[43m,[49m[43m [49m[43muid[49m[43m,[49m[43m [49m[43mumask[49m[43m,[49m
[1;32m    979[0m [43m                        [49m[43mstart_new_session[49m[43m)[49m
[1;32m    980[0m [38;5;28;01mexcept[39;00m:
[1;32m    981[0m     [38;5;66;03m# Cleanup if the child failed starting.[39;00m

File [0;32m/usr/local/lib/python3.10/subprocess.py:1863[0m, in [0;36mPopen._execute_child[0;34m(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)[0m
[1;32m   1862[0m         err_msg [38;5;241m=[39m os[38;5;241m.[39mstrerror(errno_num)
[0;32m-> 1863[0m     [38;5;28;01mraise[39;00m child_exception_type(errno_num, err_msg, err_filename)
[1;32m   1864[0m [38;5;28;01mraise[39;00m child_exception_type(err_msg)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: PosixPath('dot')

The above exception was the direct cause of the following exception:

[0;31mExecutableNotFound[0m                        Traceback (most recent call last)
Cell [0;32mIn[6], line 2[0m
[1;32m      1[0m [38;5;66;03m# ãƒ‘ã‚¹å›³[39;00m
[0;32m----> 2[0m [43msemopy[49m[38;5;241;43m.[39;49m[43msemplot[49m[43m([49m[43mmodel[49m[43m,[49m[43m [49m[43mfilename[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m/tmp/path_diagram.png[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/__w/notes/notes/.venv/lib/python3.10/site-packages/semopy/plot.py:126[0m, in [0;36msemplot[0;34m(mod, filename, inspection, plot_covs, plot_exos, images, engine, latshape, plot_ests, std_ests, show)[0m
[1;32m    124[0m             label [38;5;241m=[39m [38;5;28mstr[39m()
[1;32m    125[0m         g[38;5;241m.[39medge(rval, lval, label[38;5;241m=[39mlabel, [38;5;28mdir[39m[38;5;241m=[39m[38;5;124m'[39m[38;5;124mboth[39m[38;5;124m'[39m, style[38;5;241m=[39m[38;5;124m'[39m[38;5;124mdashed[39m[38;5;124m'[39m)
[0;32m--> 126[0m [43mg[49m[38;5;241;43m.[39;49m[43mrender[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mview[49m[38;5;241;43m=[39;49m[43mshow[49m[43m)[49m
[1;32m    127[0m [38;5;28;01mreturn[39;00m g

File [0;32m/__w/notes/notes/.venv/lib/python3.10/site-packages/graphviz/_tools.py:185[0m, in [0;36mdeprecate_positional_args.<locals>.decorator.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    177[0m     wanted [38;5;241m=[39m [38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m=[39m[38;5;132;01m{[39;00mvalue[38;5;132;01m!r}[39;00m[38;5;124m'[39m
[1;32m    178[0m                        [38;5;28;01mfor[39;00m name, value [38;5;129;01min[39;00m deprecated[38;5;241m.[39mitems())
[1;32m    179[0m     warnings[38;5;241m.[39mwarn([38;5;124mf[39m[38;5;124m'[39m[38;5;124mThe signature of [39m[38;5;132;01m{[39;00mfunc_name[38;5;132;01m}[39;00m[38;5;124m will be reduced[39m[38;5;124m'[39m
[1;32m    180[0m                   [38;5;124mf[39m[38;5;124m'[39m[38;5;124m to [39m[38;5;132;01m{[39;00msupported_number[38;5;132;01m}[39;00m[38;5;124m positional arg[39m[38;5;132;01m{[39;00ms_[38;5;132;01m}[39;00m[38;5;132;01m{[39;00mqualification[38;5;132;01m}[39;00m[38;5;124m'[39m
[1;32m    181[0m                   [38;5;124mf[39m[38;5;124m'[39m[38;5;124m [39m[38;5;132;01m{[39;00m[38;5;28mlist[39m(supported)[38;5;132;01m}[39;00m[38;5;124m: pass [39m[38;5;132;01m{[39;00mwanted[38;5;132;01m}[39;00m[38;5;124m as keyword arg[39m[38;5;132;01m{[39;00ms_[38;5;132;01m}[39;00m[38;5;124m'[39m,
[1;32m    182[0m                   stacklevel[38;5;241m=[39mstacklevel,
[1;32m    183[0m                   category[38;5;241m=[39mcategory)
[0;32m--> 185[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/__w/notes/notes/.venv/lib/python3.10/site-packages/graphviz/rendering.py:122[0m, in [0;36mRender.render[0;34m(self, filename, directory, view, cleanup, format, renderer, formatter, neato_no_op, quiet, quiet_view, outfile, engine, raise_if_result_exists, overwrite_source)[0m
[1;32m    118[0m filepath [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msave(filename, directory[38;5;241m=[39mdirectory, skip_existing[38;5;241m=[39m[38;5;28;01mNone[39;00m)
[1;32m    120[0m args[38;5;241m.[39mappend(filepath)
[0;32m--> 122[0m rendered [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_render[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    124[0m [38;5;28;01mif[39;00m cleanup:
[1;32m    125[0m     log[38;5;241m.[39mdebug([38;5;124m'[39m[38;5;124mdelete [39m[38;5;132;01m%r[39;00m[38;5;124m'[39m, filepath)

File [0;32m/__w/notes/notes/.venv/lib/python3.10/site-packages/graphviz/_tools.py:185[0m, in [0;36mdeprecate_positional_args.<locals>.decorator.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    177[0m     wanted [38;5;241m=[39m [38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m=[39m[38;5;132;01m{[39;00mvalue[38;5;132;01m!r}[39;00m[38;5;124m'[39m
[1;32m    178[0m                        [38;5;28;01mfor[39;00m name, value [38;5;129;01min[39;00m deprecated[38;5;241m.[39mitems())
[1;32m    179[0m     warnings[38;5;241m.[39mwarn([38;5;124mf[39m[38;5;124m'[39m[38;5;124mThe signature of [39m[38;5;132;01m{[39;00mfunc_name[38;5;132;01m}[39;00m[38;5;124m will be reduced[39m[38;5;124m'[39m
[1;32m    180[0m                   [38;5;124mf[39m[38;5;124m'[39m[38;5;124m to [39m[38;5;132;01m{[39;00msupported_number[38;5;132;01m}[39;00m[38;5;124m positional arg[39m[38;5;132;01m{[39;00ms_[38;5;132;01m}[39;00m[38;5;132;01m{[39;00mqualification[38;5;132;01m}[39;00m[38;5;124m'[39m
[1;32m    181[0m                   [38;5;124mf[39m[38;5;124m'[39m[38;5;124m [39m[38;5;132;01m{[39;00m[38;5;28mlist[39m(supported)[38;5;132;01m}[39;00m[38;5;124m: pass [39m[38;5;132;01m{[39;00mwanted[38;5;132;01m}[39;00m[38;5;124m as keyword arg[39m[38;5;132;01m{[39;00ms_[38;5;132;01m}[39;00m[38;5;124m'[39m,
[1;32m    182[0m                   stacklevel[38;5;241m=[39mstacklevel,
[1;32m    183[0m                   category[38;5;241m=[39mcategory)
[0;32m--> 185[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/__w/notes/notes/.venv/lib/python3.10/site-packages/graphviz/backend/rendering.py:326[0m, in [0;36mrender[0;34m(engine, format, filepath, renderer, formatter, neato_no_op, quiet, outfile, raise_if_result_exists, overwrite_filepath)[0m
[1;32m    322[0m cmd [38;5;241m+[39m[38;5;241m=[39m args
[1;32m    324[0m [38;5;28;01massert[39;00m filepath [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m, [38;5;124m'[39m[38;5;124mwork around pytype false alarm[39m[38;5;124m'[39m
[0;32m--> 326[0m [43mexecute[49m[38;5;241;43m.[39;49m[43mrun_check[49m[43m([49m[43mcmd[49m[43m,[49m
[1;32m    327[0m [43m                  [49m[43mcwd[49m[38;5;241;43m=[39;49m[43mfilepath[49m[38;5;241;43m.[39;49m[43mparent[49m[43m [49m[38;5;28;43;01mif[39;49;00m[43m [49m[43mfilepath[49m[38;5;241;43m.[39;49m[43mparent[49m[38;5;241;43m.[39;49m[43mparts[49m[43m [49m[38;5;28;43;01melse[39;49;00m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m,[49m
[1;32m    328[0m [43m                  [49m[43mquiet[49m[38;5;241;43m=[39;49m[43mquiet[49m[43m,[49m
[1;32m    329[0m [43m                  [49m[43mcapture_output[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m    331[0m [38;5;28;01mreturn[39;00m os[38;5;241m.[39mfspath(outfile)

File [0;32m/__w/notes/notes/.venv/lib/python3.10/site-packages/graphviz/backend/execute.py:81[0m, in [0;36mrun_check[0;34m(cmd, input_lines, encoding, quiet, **kwargs)[0m
[1;32m     79[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m e:
[1;32m     80[0m     [38;5;28;01mif[39;00m e[38;5;241m.[39merrno [38;5;241m==[39m errno[38;5;241m.[39mENOENT:
[0;32m---> 81[0m         [38;5;28;01mraise[39;00m ExecutableNotFound(cmd) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01me[39;00m
[1;32m     82[0m     [38;5;28;01mraise[39;00m
[1;32m     84[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m quiet [38;5;129;01mand[39;00m proc[38;5;241m.[39mstderr:

[0;31mExecutableNotFound[0m: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH

