Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x = np.linspace(-10, 10, 15)
y = 1 / (1 + np.exp(-x))

plt.scatter(x, y)

from scipy.stats import spearmanr, pearsonr
from ordinalcorr import polychoric
print(f"{pearsonr(x, y).statistic=:.3f}")
print(f"{spearmanr(x, y).statistic=:.3f}")
print(f"{polychoric(x, y)=:.3f}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m x [38;5;241m=[39m [43mnp[49m[38;5;241m.[39mlinspace([38;5;241m-[39m[38;5;241m10[39m, [38;5;241m10[39m, [38;5;241m15[39m)
[1;32m      2[0m y [38;5;241m=[39m [38;5;241m1[39m [38;5;241m/[39m ([38;5;241m1[39m [38;5;241m+[39m np[38;5;241m.[39mexp([38;5;241m-[39mx))
[1;32m      4[0m plt[38;5;241m.[39mscatter(x, y)

[0;31mNameError[0m: name 'np' is not defined

